name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine package manager
        id: setup
        run: |
          if [ -f "yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_ENV
          elif [ -f "package.json" ]; then
            echo "manager=npm" >> $GITHUB_ENV
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Install dependencies
        run: |
          if [ "$MANAGER" = "yarn" ]; then
            yarn install
          elif [ "$MANAGER" = "npm" ]; then
            npm ci
          fi
        env:
          MANAGER: ${{ env.manager }}

      - name: Build
        run: |
          if [ "$MANAGER" = "yarn" ]; then
            yarn build
          elif [ "$MANAGER" = "npm" ]; then
            npm run build
          fi
        env:
          MANAGER: ${{ env.manager }}
